### ISSUE TITLE
Server internal compile error show in web browser after using vgroute

### ISSUE THREAD

**Issue by darkautism** [vugu/vgrouter#2]
Previous example only print compile error in console.
![image](https://user-images.githubusercontent.com/3898040/77984854-5d17cd00-7345-11ea-99ea-63eba6da1e41.png)

After using vgroute

![image](https://user-images.githubusercontent.com/3898040/77984590-913ebe00-7344-11ea-84c1-8a37e5157d9c.png)

This behavior is expected?

But it is good idea export error by http if we using a dev server with a debug dev panel like webpack dev server.

**Comment by bradleypeabody** [comment]
There should be no difference in how error messages are printed due to using vgrouter.  Although depending on if errors are occurring during the build of devserver.go or when it builds main.wasm upon page refresh.

If problems keep up and you'd like me to look more please post the code you're using along with the error message(s).

Also, in case you haven't seen it already, you'll want to be familiar with the instructions here: https://github.com/vugu/vugu/wiki/Refactor-Notes---Sep-2019
